config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :persons

  resources :addresses
  resources :events
  resources :donations
  resources :memberships
  resources :roles

  resources :interests
  resources :educations
  resources :expertises
  resources :schools 
  
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root 'user_sessions#new'

end

app/models/membership.rb
class Membership
  include Mongoid::Document
  
  field :lvl, type: String
   validates :lvl,  presence: true, length: { maximum: 50 } ,format: { with: /\A[a-zA-Z ]+\z/,
    message: "only allows letters and white space" }

  field :amt, type: String

  has_and_belongs_to_many :persons, autosave: true
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  def index
    	@memberships = Membership.all
  end

  def show
    @membership = Membership.find(params[:id])

    @membership.persons.each do |p|
      puts "Displaying user's membership => #{p.first_name}"
    end

    return @membership
  end

  def new
  	@membership = Membership.new
  end

  def edit
    @membership = Membership.find(params[:id])
  end

  def create
  	    @membership = Membership.new(membership_params)
    
    @persons = []

    
    participatingkv = participating_params
    participatingpeoplevalues = participatingkv[:participating_people ]
    puts "I am saying something here"

    # Doners cannot work without null donations, still to prevent error, allowed null
    if participatingpeoplevalues
      participatingpeoplevalues.each do |pv|
        @person = Person.where(:_id => pv).first
        puts "THis person's name is #{@person.first_name}"
        @persons.push(@person)
      end      
    end
    
    # Replace @donation.persons
    @membership.persons = @persons
    

    if @membership.save
      redirect_to @membership
      flash[:success] = "Added successfully!"
    else
      render 'new'
    end
  end

  def update
    @membership = Membership.find(params[:id])

     @persons = []

    participatingkv = participating_params
    participatingkvuservalues = participatingkv[:participating_people]

    #@persons << Person.where(:_id => participatingkvuservalues).first

    if participatingkvuservalues
      participatingkvuservalues.each do |pv|
        @person = Person.where(:_id => pv).first
        #puts "THis person's name is #{@person.name}"
        @persons.push(@person)
      end      
    end
      
    @membership.persons = @persons

    if @membership.update(membership_params)
      redirect_to @membership
      flash[:success] = "Updated successfully!"
    else
      render 'edit'
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    redirect_to memberships_path
  end

  private
  def membership_params
  	params.require(:membership).permit( :lvl, :amt, :participating_people => [])
  end

  private
  def participating_params
    params.permit(:participating_people => [])
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_membership.html.erb
<div class="container">
<div class ="row">
<div class="col-sm-8"> 

<%= form_for(@membership, :html => {class: "form-horizontal", role: "form"} ) do |p| %>

    <% if @membership.errors.any? %>
        <div id="error_explanation">

          <h2><%= pluralize( @membership.errors.count, "error") %> prohibited this msg from being saved:</h2>

          <ul>
            <% @membership.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :membershiplevel,"Membership level:" %></div>
      <div class="col-xs-4"><%= p.text_field :lvl, :class => 'form-control'%></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :membershipamount,"Amount:"%></div>
      <div class="col-xs-4"><%= p.text_field :amt, :class => 'form-control' %></div>
    </div>



     <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :users, 'Members:' %></div>
      <div class="col-xs-4">

        <%= select_tag "participating_people",
                       options_from_collection_for_select(Person.all, 'id', 'first_name', @membership.persons.map{ |j| j.id }), :multiple => true, :class => "form-control" %>
      </div>
    </div>



   <div class="container margin-top-25">

      <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          Save <i class="icon-repeat"></i>
      <% end %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-danger"} %>
    </div>

<% end %>
</div>
</div>
</div>

app/views/memberships/edit.html.erb
<h1>Edit Membership</h1>
<%= render 'membership' %>

app/views/memberships/index.html.erb
<h1> Membership</h1>

<div class="container">
    <div class="row col-xs-12 margin-top-25">
        <span class="col-xs-9"></span>
        <span class="col-xs-1"><%= link_to '  New', new_membership_path, :class =>'glyphicon glyphicon-plus align: left', :title=>'Add New Member' %></span>
	<input type="text" id="search" placeholder="Type to search..." />
    </div> 

<table id="table" class="table-striped table-bordered table-hover table-condensed col-xs-12 margin-top-05">
    <thead>
    <tr>
      <th>Member</th>
      <th>Membership Level</th>
        <th>Amount</th>
      <th colspan="6">Actions</th>
    </tr>
    </thead>
<tbody>
   <% @memberships.each do |membership| %>
        <tr>
            <td>
            <% membership.persons.each do |p| %>
                <%= p.first_name%>&nbsp;<%= p.last_name %>
            <% end %>            
            </td>
            <td><%= membership.lvl %></td>
            <td><%= membership.amt %></td>
            <td><%= link_to '', membership_path(membership), :class => 'glyphicon glyphicon-eye-open', :title => 'Show' %></td>
            <td><%= link_to '', edit_membership_path(membership), :class => 'glyphicon glyphicon-pencil', :title => 'Edit' %></td>
            <td><%= link_to '', membership_path(membership),

        method: :delete,
            data: {confirm: 'Are you sure?'},
        :class => 'glyphicon glyphicon-trash',
            :title => 'Delete'
             %></td>
        </tr>
    <% end %>
 </tbody>
</table>

</div>
</div>
</div>

app/views/memberships/new.html.erb
<h1>Create New Member</h1>
<%= render 'membership' %>

app/views/memberships/show.html.erb
<div class="row margin-top-10">
  <div class="col-xs-2"><strong>Members:</strong></div>
  <div class="col-xs-10"><% @membership.persons.each do |p| %>
                <%= p.first_name %> <%= p.last_name %>
            <% end %> 
  </div>
</div>

<div class="row margin-top-10">
  <div class="col-xs-2"><strong>Membership Level:</strong></div>
  <div class="col-xs-10"><%= @membership.lvl %></div>
</div>

<div class="row margin-top-10">
  <div class="col-xs-2"> <strong>Amount:</strong></div>
  <div class="col-xs-10"> <%= @membership.amt%></div>
</div>




<div class="container margin-top-25">
  <%= link_to 'Edit', edit_membership_path(@membership), class: "btn btn-primary" %>
  <%= link_to 'Ok', memberships_path, class: "btn btn-primary" %>
</div>