config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :persons

  resources :addresses
  resources :events
  resources :donations
  resources :memberships
  resources :roles

  resources :interests
  resources :educations
  resources :expertises
  resources :schools 
  
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root 'user_sessions#new'

end

app/models/donation.rb
class Donation
  include Mongoid::Document
  # TODO: Change to proper type
  field :monetary_value, type: String
   validates :monetary_value,  presence: true, length: { maximum: 50 },format: { with: /\A[0-9]+\z/,
    message: "only allows Numbers" }
  field :date, type: String
   validates :date,  presence: true, length: { maximum: 50 } ,format: { with: /\d{4}\-\d{2}\-\d{2}/,
    message: "must be date and time"}
  field :type, type: String
    validates :type,  presence: true, length: { maximum: 50 } ,format: { with: /\A[a-zA-Z ]+\z/,
    message: "only allows letters and white space" }
  field :description, type: String
    validates :description,  presence: true, length: { maximum: 50 } ,format: { with: /\A[a-zA-Z ]+\z/,
    message: "only allows letters and white space" }
  has_and_belongs_to_many :persons, autosave: true

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
    def index
    @donations = Donation.all
  end

  def show
    @donation = Donation.find(params[:id])

    #@donation.persons.each do |p|
    #  puts "Show is showing a showey person => #{p.name}"
    #end

    return @donation
  end

  def new
    @donation = Donation.new
  end

  def edit
    @donation = Donation.find(params[:id])
  end

  def create
    @donation = Donation.new(donation_params)
    
    @persons = []

    
    participatingkv = participating_params
    participatingpeoplevalues = participatingkv[:participating_people ]
    puts "I am saying something here"

    # Doners cannot work without null donations, still to prevent error, allowed null
    if participatingpeoplevalues
      participatingpeoplevalues.each do |pv|
        @person = Person.where(:_id => pv).first
        #puts "THis person's name is #{@person.name}"
        @persons.push(@person)
      end      
    end
    
    # Replace @donation.persons
    @donation.persons = @persons
    

    if @donation.save
      redirect_to @donation
      flash[:success] = "Added successfully!"
    else
      render 'new'
    end

  end

  def update
    @donation = Donation.find(params[:id])

    @persons = []
    participatingkv = participating_params
    participatingpeoplevalues = participatingkv[:participating_people ]

    
    participatingpeoplevalues.each do |pv|
      @person = Person.where(:_id => pv).first
      puts "THis person's name is #{@person.name}"
      @persons.push(@person)
    end

    # Replace @donation.persons with this new value
    @donation.persons = @persons

    if @donation.update(donation_params)
      redirect_to @donation
      flash[:success] = "Updated successfully!"
    else
      render 'edit'
    end
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    redirect_to donations_path
  end

  private
  def donation_params
    params.require(:donation).permit(:monetary_value, :date, :type, :description, :participating_people => [])
  end

  private
  def participating_params
    params.permit(:participating_people => [])
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<script>
$(function(){
    $( ".datetimepicker" ).datepicker({
    dateFormat: "yy-mm-dd"
    });
});
</script>
<%= form_for(@donation, :html => {class: "form-horizontal", role: "form"} ) do |p| %>

       <% if @donation.errors.any? %>
        <div id="error_explanation">

          <h2><%= pluralize( @donation.errors.count, "error") %> prohibited this msg from being saved:</h2>

          <ul>
            <% @donation.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :monetary_value %></div>
      <div class="col-xs-4"><%= p.text_field :monetary_value, :class => 'form-control'%></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :date%></div>
      <div class="col-xs-4"><%= p.text_field :date, :class => "datetimepicker form-control" %></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :type%></div>
      <div class="col-xs-4"><%= p.text_field :type, :class => "form-control" %></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :description%></div>
      <div class="col-xs-4"><%= p.text_area :description, :class => "form-control" %></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :persons, 'Doners' %></div>
      <div class="col-xs-4">

        <%= select_tag "participating_people",
                       options_from_collection_for_select(Person.all, 'id', 'first_name', @donation.persons.map{ |j| j.id }), :multiple => true, :class => "form-control" %>
      </div>
    </div>


    <div class="container margin-top-25">

      <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          Save <i class="icon-repeat"></i>
      <% end %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-danger"} %>
    </div>


<% end %>

app/views/donations/edit.html.erb
<%= render 'donation' %>

app/views/donations/index.html.erb
<h1> Donation </h1>


<div class="container">
	<div class="row col-xs-12 margin-top-25">
		<span class="col-xs-9"></span>
 		<span class="col-xs-1"><%= link_to '  New', new_donation_path, :class =>'glyphicon glyphicon-plus align: left', :title=>'New Donation' %></span>
 		<input type="text" id="search" placeholder="Type to search..." />
 	</div>
  <div class="row">
	<div class="col-xs-12">
	<table  id="table" class="table-striped table-bordered table-hover table-condensed col-xs-12 margin-top-05"> 
	  <thead>
		<tr >
          <th>Monetary Value</th>
          <th>Date</th>
          <th>Type</th>
          <th>Description</th>
		  <th colspan="3">Actions</th>
		</tr>
	  </thead>
	  <tbody>

		<% @donations.each do |donation| %>
          <tr>
			<td><%= donation.monetary_value %></td>
			<td><%= donation.date%></td>
			<td><%= donation.type%></td>
			<td><%= donation.description%></td>
            <td><%= link_to '', donation_path(donation), :class => 'glyphicon glyphicon-eye-open', :title => 'Show' %></td>
            <td><%= link_to '', edit_donation_path(donation), :class => 'glyphicon glyphicon-pencil', :title => 'Edit' %></td>
			<td>
			  <%= link_to '', donation_path(donation),				
			    method: :delete,
				data: {confirm: 'Are you sure?'},
				:class => 'glyphicon glyphicon-trash',
				:title => 'Delete'
				%>
			</td>
          </tr>
		<% end %>
	  </tbody>
	</table>
     
	</div>
  </div>
</div>

app/views/donations/new.html.erb
<%= render 'donation' %>

app/views/donations/show.html.erb
<div class="row margin-top-10">
  <div class="col-xs-2"><strong>Monetary Value:</strong></div>
  <div class="col-xs-10"><%= @donation.monetary_value %></div>
</div>

<div class="row margin-top-10">
  <div class="col-xs-2"><strong>Date:</strong></div>
  <div class="col-xs-10"><%= @donation.date %></div>
</div>

<div class="row margin-top-10">
  <div class="col-xs-2"><strong>Type:</strong></div>
  <div class="col-xs-10"><%=  @donation.type %></div>
</div>

<div class="row margin-top-10">
  <div class="col-xs-2"><strong>Description:</strong></div>
  <div class="col-xs-10"><%=  @donation.description %></div>
</div>

<h4 class="text-info">Doners</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <table class="table-striped table-bordered table-hover table-condensed">
        <thead>
        <tr>
          <th>Name</th>
        </tr>
        </thead>
        <tbody>
        <% @donation.persons.each do |p| %>
            <tr>
              <td><%= p.first_name %>&nbsp; <%= p.last_name %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="container margin-top-25">
  <%= link_to 'Edit', edit_donation_path(@donation), class: "btn btn-primary" %>
  <%= link_to 'Ok', donations_path , class: "btn btn-primary" %>
</div>