config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :persons

  resources :addresses
  resources :events
  resources :donations
  resources :memberships
  resources :roles

  resources :interests
  resources :educations
  resources :expertises
  resources :schools 
  
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root 'user_sessions#new'

end

app/models/school.rb
class School
  include Mongoid::Document
  # TODO: Change to proper type
  field :SchoolName, type: String
   validates :SchoolName,  presence: true, length: { maximum: 50 } ,format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
       
  field :ContactNumber, type: String
    validates :ContactNumber,  presence: true, length: { maximum: 50 },format: { with: /\A[0-9]+\z/,
    message: "only allows Numbers" }


  field :street, type: String

  field :city, type: String

  field :state, type: String

  field :county, type: String

  field :zip, type: String



  def address_name
    "#{street}, #{city}, #{state}, #{county}, #{zip}"
  end
      
  has_and_belongs_to_many :persons, autosave: true

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def show
    @school = School.find(params[:id])

    @school.persons.each do |p|
      
    end

    return @school
  end

  def new
    @school = School.new
  end

  def edit
    @school = School.find(params[:id])
  end

  def create
    @school = School.new(event_params)
    
    @persons = []

    
    participatingkv = participating_params
    participatingpeoplevalues = participatingkv[:participating_people ]

    # Doners cannot work without null donations, still to prevent error, allowed null
    if participatingpeoplevalues
      participatingpeoplevalues.each do |pv|
        @person = Person.where(:_id => pv).first
        @persons.push(@person)
      end      
    end
    
    # Replace @donation.persons
    @school.persons = @persons

      if @school.save
        flash[:success] = "Added successfully!"
      redirect_to @school
    else
      render 'new'
    end

  end

  def update
    @school = School.find(params[:id])

     @persons = []

    participatingkv = participating_params
    participatingkvuservalues = participatingkv[:participating_people]

    #@persons << Person.where(:_id => participatingkvuservalues).first

    if participatingkvuservalues
      participatingkvuservalues.each do |pv|
        @person = Person.where(:_id => pv).first
        #puts "THis person's name is #{@person.name}"
        @persons.push(@person)
      end      
    end

    if @school.update(event_params)
      flash[:success] = "update successfully!"
      redirect_to @school
    else
      render 'edit'
    end
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy

    redirect_to schools_path
  end

  private
  def event_params
    params.require(:school).permit(:SchoolName, :ContactNumber,:street,:city, :state,:county,:zip, :participating_people => [])
  end

  private
  def participating_params
    params.permit(:participating_people => [])
  end

end

app/views/schools/_school.html.erb
<div class="container">
<div class ="row">
<div class="col-sm-8"> 

<%= form_for(@school, :html => {class: "form-horizontal", role: "form"} ) do |p| %>

     

    <% if @school.errors.any? %>
        <div id="error_explanation">

          <h2><%= pluralize(@school.errors.count, "error") %> prohibited this msg from being saved:</h2>

          <ul>
            <% @school.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :SchoolName,"School Name:" %></div>
      <div class="col-xs-4"><%= p.text_field :SchoolName, :class => 'form-control'%></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :ContactNumber, "Contact Number:" %></div>
      <div class="col-xs-4"><%= p.text_field :ContactNumber, :class => 'form-control' %></div>
    </div>

    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :users, 'Students:' %></div>
      <div class="col-xs-4">

        <%= select_tag "participating_people",
                       options_from_collection_for_select(Person.all, 'id', 'first_name', @school.persons.map{ |j| j.id }), :multiple => true, :class => "form-control" %>
      </div>
    </div>

    <h3> Address</h3>
     <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :street %></div>
      <div class="col-xs-4"><%= p.text_field :street, :class => 'form-control'%></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :city%></div>
      <div class="col-xs-4"><%= p.text_field :city, :class => "form-control" %></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :state%></div>
      <div class="col-xs-4"><%= p.text_field :state, :class => "form-control" %></div>
    </div>


    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :county%></div>
      <div class="col-xs-4"><%= p.text_field :county, :class => "form-control" %></div>
    </div>

    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :zip %></div>
      <div class="col-xs-4"><%= p.text_field :zip, :class => "form-control" %></div>
    </div>



   <div class="container margin-top-25">

      <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          Save <i class="icon-repeat"></i>
      <% end %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-danger"} %>
    </div>

<% end %>
</div>
</div>
</div>

app/views/schools/edit.html.erb
<h1>Edit School</h1>
<%= render 'school' %>

app/views/schools/index.html.erb
<div class="container">
    <div class="row col-xs-12 margin-top-25">
        <span class="col-xs-9"></span>
        <span class="col-xs-1"><%= link_to '  New', new_school_path, :class =>'glyphicon glyphicon-plus align: left', :title=>'Add School' %></span>
        <input type="text" id="search" placeholder="Type to search..." />
    
    </div> 

<table id="table" class="table-striped table-bordered table-hover table-condensed col-xs-12 margin-top-05">
    <h2>Schools</h2>
    <thead>
    <tr>
      <th>School</th>
      <th >Contact Number</th>
      <th colspan="6">Actions</th>
    </tr>
    </thead>
<tbody>
   <% @schools.each do |school| %>
        <tr>
            <td><%= school.SchoolName %></td>
            <td><%= school.ContactNumber %></td>
            <td><%= link_to '', school_path(school), :class => 'glyphicon glyphicon-eye-open', :title => 'Show' %></td>
            <td><%= link_to '', edit_school_path(school), :class => 'glyphicon glyphicon-pencil', :title => 'Edit' %></td>
            <td><%= link_to '', school_path(school),

        method: :delete,
            data: {confirm: 'Are you sure?'},
        :class => 'glyphicon glyphicon-trash',
            :title => 'Delete'
             %></td>
        </tr>
    <% end %>
 </tbody>
</table>

</div>
</div>
</div>

app/views/schools/new.html.erb
<h1>Create New School</h1>
<%= render 'school' %>

app/views/schools/show.html.erb
<div class="row margin-top-10">
  <div class="col-xs-2"><strong>School Name:</strong></div>
  <div class="col-xs-1"> <%= @school.SchoolName %></div>
</div>

<div class="row margin-top-10">
  <div class="col-xs-2"><strong>Contact Number:</strong></div>
  <div class="col-xs-1"><%= @school.ContactNumber %></div>
</div>

<div class="row margin-top-10">
  <div class="col-xs-2"><strong>Contact Address:</strong></div>
  <div class="col-xs-10"><%= @school.address_name %></div>
</div>

<div class="row margin-top-10">
	<h4>Student Count  &nbsp;<%= @school.persons.count %></h4>
  <div class="col-xs-2"><strong>Students:</strong></div>
  <div class="col-xs-10"><% @school.persons.each do |p| %>

                <%= p.first_name %> <%= p.last_name %><br />
            <% end %> 
  </div>
</div>

<div class="container margin-top-25">
  <%= link_to 'Edit', edit_school_path(@school), class: "btn btn-primary" %>
  <%= link_to 'Ok', schools_path , class: "btn btn-primary" %>
</div>