config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :persons

  resources :addresses
  resources :events
  resources :donations
  resources :memberships
  resources :roles

  resources :interests
  resources :educations
  resources :expertises
  resources :schools 
  
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root 'user_sessions#new'

end

app/models/education.rb
class Education
  include Mongoid::Document
  # TODO: Change to proper type
  field :educationlevel, type: String
   validates :educationlevel,  presence: true, length: { maximum: 50 } ,format: { with: /\A[a-zA-Z ]+\z/,
    message: "only allows letters and white space" }
  
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  def index
    @educations = Education.all
  end

  def show
    @education = Education.find(params[:id])

    @persons = Person.all

    @pp = []

     @persons.each do |p| 
      p.educations.each do |i| 
        if i.educationlevel ==  @education.educationlevel
        puts "Show is showing a showey person Interest => #{i.educationlevel}"
        @pp.push(p) 
        end
      end
    end   
    return @PP  
  end

  def new
    @education = Education.new
  end

  def edit
    @education = Education.find(params[:id])
  end

  def create
    @education = Education.new(education_params)
    
   
    if @education.save
      redirect_to @education
      flash[:success] = "Added successfully!"
    else
      render 'new'
    end

  end

  def update
    @education = Education.find(params[:id])

  
    if @education.update(education_params)
      redirect_to @education
      flash[:success] = "update successfully!"
    else
      render 'edit'
    end
  end

  def destroy
    @education = Education.find(params[:id])
    @education.destroy

    redirect_to educations_path
  end

  private
  def education_params
    params.require(:education).permit(:educationlevel)
  end

end

app/views/educations/_education.html.erb
<div class="container">
<div class ="row">
<div class="col-sm-8"> 

<%= form_for(@education, :html => {class: "form-horizontal", role: "form"} ) do |p| %>

    <% if @education.errors.any? %>
        <div id="error_explanation">

          <h2><%= pluralize( @education.errors.count, "error") %> prohibited this msg from being saved:</h2>

          <ul>
            <% @education.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row margin-top-15">
      <div class="col-xs-2"><%= p.label :educationlevel, "Education Level:" %></div>
      <div class="col-xs-4"><%= p.text_field :educationlevel, :class => 'form-control'%></div>
    </div>


   <div class="container margin-top-25">

      <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          Save <i class="icon-repeat"></i>
      <% end %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-danger"} %>
    </div>

<% end %>
</div>
</div>
</div>



app/views/educations/edit.html.erb
<h1>Edit</h1>
<%= render 'education' %>

app/views/educations/index.html.erb
<h1> Education </h1>
<div class="container">
    <div class="row col-xs-12 margin-top-25">
        <span class="col-xs-9"></span>
        <span class="col-xs-1"><%= link_to '  New', new_education_path, :class =>'glyphicon glyphicon-plus align: left', :title=>'Add Educaton' %></span>
        <input type="text" id="search" placeholder="Type to search..." />
    </div> 

<table id="table" class="table-striped table-bordered table-hover table-condensed col-xs-12 margin-top-05">
    <thead>
    <tr>
       <th>Education level</th>
        <th colspan="6">Actions</th>
    </tr>
    </thead>
<tbody>
   <% @educations.each do |education| %>
        <tr>
            <td><%= education.educationlevel %></td>
            <td><%= link_to '', education_path(education), :class => 'glyphicon glyphicon-eye-open', :title => 'Show' %></td>
            <td><%= link_to '', edit_education_path(education), :class => 'glyphicon glyphicon-pencil', :title => 'Edit' %></td>
            <td><%= link_to '', education_path(education),

        method: :delete,
            data: {confirm: 'Are you sure?'},
        :class => 'glyphicon glyphicon-trash',
            :title => 'Delete'
             %></td>
        </tr>
    <% end %>
 </tbody>
</table>

</div>
</div>
</div>



app/views/educations/new.html.erb

<%= render 'education' %>

app/views/educations/show.html.erb
<div class="row margin-top-10">
  <div class="col-xs-1"><strong>Education Level:</strong></div>
  <div class="col-xs-1"><%= @education.educationlevel %></div>
</div>
<hr>

<h4 class="text-info">Persons</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <table class="table-striped table-bordered table-hover table-condensed">
        <thead>
        <tr>
          <th>Name</th>
          
        </tr>
        </thead>
        <tbody>
        <% @pp.each do |p| %>
            <tr>
              <td><%= p.first_name   %> <%=  p.last_name %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row margin-top-10">
  <div class="col-xs-1"><strong>Total:</strong></div>
  <div class="col-xs-1"><%=@pp.size %></div>
</div>
<hr>

<div class="container margin-top-25">
  <%= link_to 'Edit', edit_education_path(@education), class: "btn btn-primary" %>
  <%= link_to 'Ok', educations_path , class: "btn btn-primary" %>
</div>
